// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sharmila_Textile_WebApp.Data;

namespace Sharmila_Textile_WebApp.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200206114227_Initiate")]
    partial class Initiate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sharmila_Textile_WebApp.Models.Staff", b =>
                {
                    b.Property<long>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("STAFF_ID")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnName("ADDRESS")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ContactNo")
                        .HasColumnName("CONTACT_NO")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("CurrentStatus")
                        .HasColumnName("CURRENT_STATUS")
                        .HasColumnType("int");

                    b.Property<string>("Nic")
                        .HasColumnName("NIC")
                        .HasColumnType("varchar(12)");

                    b.Property<string>("StaffName")
                        .HasColumnName("NIC")
                        .HasColumnType("varchar(12)");

                    b.HasKey("StaffId");

                    b.ToTable("STAFF");
                });

            modelBuilder.Entity("Sharmila_Textile_WebApp.Models.StaffAttachment", b =>
                {
                    b.Property<long>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ATTACHMENT_ID")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttachmentName")
                        .HasColumnName("ATTACHMENT_NAME")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("AttachmentPath")
                        .HasColumnName("ATTACHMENT_PATH")
                        .HasColumnType("varchar(max)");

                    b.Property<long>("StaffId")
                        .HasColumnName("STAFF_ID")
                        .HasColumnType("bigint");

                    b.HasKey("AttachmentId");

                    b.HasIndex("StaffId");

                    b.ToTable("STAFF_ATTACHMENT");
                });

            modelBuilder.Entity("Sharmila_Textile_WebApp.Models.StaffAttachment", b =>
                {
                    b.HasOne("Sharmila_Textile_WebApp.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
